spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    serialization:
      # Date???????? ?????LocalDateTime?????JacksonCustomizerConfig????
      write-dates-as-timestamps: true
    #????????
    default-property-inclusion: non_empty
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/txt2mysql?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  application:
    name: consumer-client

failOnMissingWebXml: false
dbshu:
  root: "C:/Users/lin/Desktop/txt-to-mysql/file"
  title: "sea"
  name: "年月日时分秒 电导率 盐度（psu） 温度（℃） 深度（m） 叶绿素（mg/L） 浊度（NTU） PH（ph） 溶解氧 声速"

