spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    serialization:
      # Date???????? ?????LocalDateTime?????JacksonCustomizerConfig????
      write-dates-as-timestamps: true
    #????????
    default-property-inclusion: non_empty
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    # 测试环境为 mysql-5.7.30 临时修改
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
  application:
    name: consumer-client

failOnMissingWebXml: false
# 此处可以废弃，根据数据库表设计来插入数据
dbshu:
  root: "C:/Users/lin/Desktop/txt-to-mysql/file"
  title: "sea"
  name: "年月日时分秒 电导率 盐度（psu） 温度（℃） 深度（m） 叶绿素（mg/L） 浊度（NTU） PH（ph） 溶解氧 声速"

